version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  checker:
    build: ./checker
    container_name: db_checker
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: postgres
    depends_on:
      db:
        condition: service_healthy
